# Generated by Django 3.2.6 on 2022-01-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
