# Generated by Django 3.2.6 on 2022-01-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('title_ru', models.CharField(max_length=128, null=True)),
                ('title_uz', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('title_ru', models.CharField(max_length=128, null=True)),
                ('title_uz', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('price_from', models.CharField(max_length=100)),
                ('price_to', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('sergeli', 'Сергелийский район'), ('mirzo-ulugbek', 'Мирзо-Улугбекский район'), ('mirabad', 'Мирабадский район'), ('bektemir', 'Бектемирский район'), ('almazar', 'Алмазарский район'), ('yashnabad', 'Яшнабадский район'), ('yunusabad', 'Юнусабадский район'), ('uchtepa', 'Учтепинский район'), ('shayhantahur', 'Шайхантахурский район'), ('chilanzar', 'Чиланзарский район'), ('yakkasaray', 'Яккасарайский район')], max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items')),
                ('wallpaper', models.ImageField(blank=True, null=True, upload_to='wallpapers')),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('mydes', models.TextField()),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.URLField(max_length=512)),
                ('working_time', models.CharField(max_length=256)),
                ('website', models.URLField()),
                ('category', models.ManyToManyField(related_name='items', to='item.CategoryModel')),
                ('tags', models.ManyToManyField(related_name='items', to='item.TagModel')),
            ],
            options={
                'verbose_name': 'study center',
                'verbose_name_plural': 'study centers',
            },
        ),
    ]
